issuer: http://127.0.0.1:5556/dex

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db


web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]

telemetry:
  http: 0.0.0.0:5558

staticClients:
- id: webtech-frontend
  redirectURIs:
  - 'http://localhost:3000'
  name: 'webtech-frontend'
  
  public: true
connectors:
- type: mockCallback
  id: mock
  name: Example
- type: github
  id: github
  name: GitHub
  config:
    clientID: 5001b9285a96a19b4d40
    clientSecret: 7ee95039220564c5b7cf502c55982a9928a79997
    redirectURI: http://127.0.0.1:5556/dex/callback

enablePasswordDB: true
